image: ruby:2.5.1

services:
  - postgres:latest

variables:
  POSTGRES_HOST: postgres
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --deployment --path vendor/bundle
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop -P
