language: ruby
env:
  - secure: "h2Lo7v3KdujOGSiAsDB/w93129hJtWO4yhWXKEqoaJcpKIX5gCuIvFx8+KPg6NEZ6TOZIi+ZJXDIkWhMrgZnUPe4Qk2K5aCioQziQQX74jToSenScRJkDzFK5xeA8liy0g/egoenyPSKhOOqacH9IBhC6fsvrWkuaSYlbkMXNs94je2yjWdMMGhe+l22Qs6KPcPRCd++R1/m/7mhmHbKCa63s3X+pzR6YQDuLt7Wl52jfZo+96HeCCRKkHzwdxGy1eLmb6HVhTRdgFUXY61Ur0A6iWSxQZ5SZqxp2K1rrPJBnWwXBkicvvbxnOSiabz4SxafPxQAk5NbxBec1lxoNGJwNYO/YEaQY1pERiParU4Cic2Otb0zqmEe9fC2aqM5ABTjevtjCwrSbd3n6ru7L90xY4a8tYYyQqITL56eDiJ4JVUAe2ml28h+u/9cvvmUuo59AEhE2kCKR31/WyKCC6DSBXaCazq/fn6/7wExUxxTZKD4xTdy/HfXBVxnqPtni0TM7YzOef3wIgfl1S92ctBuMwF1I94mvEw2mWZuYXiRp8FzNCPAn3nVT5fGp0Hz6dEEHXbw6gFg0ynJpHhLLRV3FYeLlooF//sbMonHrURXUrU2Fqxnn9JVcss0CgeITr16tNJ5+DBIFy06XGUaaYLlveZdSI70n9me4tnSkf0="
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
  - echo $RAILS_MASTER_KEY
  - echo $JAT
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
