language: ruby
env:
  - secure: uIcNaSngynNeB1EYTTInBixDFI1EQ93OAN0hmRK6GeEx6k3cMEHzJgK5rcod5Qwd4hs6mTPj7zJzbhKCsD8nlMmAOV305rJiNZ/XDaDDQyvWtfG6qNXKBbCfqHofxg4N4u1lU5qajCmlqTvEfKv0329A3KeSwe/fSbji+S6ToRYbUShOVYOC0zaRpUoFcogC6Q0YGFHKMcHQDsG99Cn7wEA++f08E/LvPB1L+g6mEPuNAy6CTD/CWdwRfzTsLHNkS2OHqSBX/dGX/tsALv0Gi3Oax8soTL2SvLl0BnXsz0F5AZMP77cTFHzh7GKCo+rpOmAcA6AuxuQceU4U2KDSR8kcfly43bJByiCq22qRJX8/l8WO1zH+Wl5DupLH0zqUoL2Yif/b+srXmv2Y5kS0o2nY3kA1wrLQRMUu1cCBn59n/JF0tG92NhriJQhU5qAjtIuXiB/E3cO3KzqrBneZUj6/kvvfliCcNiEQ855VqS7UKS3OumPv0MY8QOO0pCyd7QSqsBB8oE8iqvex5sJmx7qlN6VJbIhh7AvCGU38tyQZEbLGounsHI1wujqTu0gktW4roxQWuhEDd2SySTgxmtx+m4QoTXZCVjCs/DLbHxIXeCM4RMIxvrbQZ4BNa2xUf18VMZOLn7hMi0zAsYaHyV2UVggC09/1uVL/6NMJUoc=
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
  - echo $RAILS_MASTER_KEY
  - echo $JAT
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
