language: ruby
env:
  - RAILS_ENV=test
  - RACK_ENV=test
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
