language: ruby
env:
  - secure: "zyTxqwxuBLn1aMejifM3MKxEcvKfTQD7dSAEJyh9bceGi1GavtTC1CziVtZH32qKp5ZUjmQKKV0mWyvLTbP+Zem1Ky+fRI57685PON55zASgdtD5oVXDekHIMWn8bbylYeUZZQgCSRt+AcJM8/ebRHX2oUNOY/h8eELRgiHsyVlJwfnO+UXJiMP/mX4FNh/xCQIyCMvdQ5EJM0V1Qns/bveC9IFDHy826F+Bbxcb53ZIZByBwKKwxQikdRp8pLbBCOVG5lFXqpL/o6NC1471UTOnChIE7/JmaFBBOJqBhWLaCEdPStKspqBq1l60v6VMgoDgLuu7k5Ba5VqAWm1Y5TzZ+IwEutkyXHMoI30rypUV/oeRG+ezuGqMmfS4JZ5XqIb91h4XnSYnxLgF6g87gr01FPryV92PALhn8EUGvREP6jx8I2F//zGGWSkoGnkW1A1/AcltFbGosk+mIFAtkDck/z/tY1pBLu9FlnsTm/t21MFG6DnDhf0qLWxZlyzqNsXAlzhC1Ge0lYLnwpuJfDuSaIP6AccnuXSZyH9BVmnKZiqoaISHl9Ez8fPTQLI92+fquwKcWePmf9CgUs0g7Ynyl7ycgcrO8T8FPPHYi56xrFE6sG2ENVJduy3BBLmpL8KfGKSemw14VNuH0y1ghgvVDn0dg3aGv9+OHSJU3tE="
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
  - echo $RAILS_MASTER_KEY
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
