language: ruby
env:
  matrix:
    secure: VKtVK8M1TBxXBqXHV4EAvlxwaxRV3qy4rtfK+Er6eDNvKM0rxT3hI5yPoqfP4DMS3aIl966cH7tUS2JvFXAvJwmIlfLl/uBd1WfVGqdYbox4ampMhnFibgDug2vECu+3QuUsa/bDkZ41Nc1R5Fs369LAJJad9QneXaHPq7fvlUzhtGlLzl0rmT989tHZug0IFjl2eqmFCU4dBS9KcfoRKwuxxTv+HQpWHMGhIQ/diRwLCbJGdpyNKC+0T2NHuwRAfr0cHPARWMpmCINkLPXcU2yZH14B3i68iJaZ0iV+S0jQ50jwAlgo68oc8u4Ky8eOdHV0DUwQSGMfNyXhgRSzUFgFDwA2wH+5BtibxgRTz/MM0Qq5jqkUA3yBJruovPkkKzBtfAc/obpDuA5SbOe3vKcZEUXxw+NUJ5pIqaug5wpPGVgDoliHwPDaGd3LHH0mv6vW73kpMewkaX6ZLFnbtw/s74ju7EbcGcd9vqDcgTmjagRt5LoJFlTo5Re6S6io1gPiRqnp4TeGR3EEV55jnBVela+g32qf/YFtu2uGsw1aXNMUrpuqn2ZiJWObyz/gKABnzVVfgvf1BW36w8NCQn1LGctG9lg9ABMQbv7K3CK6Ez1l4RsQjRQY9FdN8qeWYHZBUxgj+hpCf9MxZGRwF29lsJ3j55ZRQjbsMSbNqns=
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
  - echo $RAILS_MASTER_KEY
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
