language: ruby
env:
  - secure: "YpOK7gGdrpL4jpdJRRRj9jW+leAM3uRUevFLpsi4qLD1YLMjyUcVhyyAGdd/nBBR4/R7lTTQocLyODNUHIajhq38g9ekai1f5AK40DUhrZj7n7MkruQmwMHY4fgOs0Fnc1/dSIzt/vV2SOFV88Qe33UM2RIU9iNkl9KhsTF2cH2yFoj0xveUkCKJGUnoOvw4oIRIaYbAh+9Jpy0ZOHFkigq0bmGEHdOYOMpoaC4POnwbTrLWAeP19r9VhrfPtcVi//pp2BXTBe52vPLK2YmMXTx4twQsKO4h3X4NVV6+icFEBG3MLsGXIORNiYMNPohzf01+76EZdN3pQ0FPar1OzOigrsOswn2aj7C8YvaqTQjWcz9cDoz/V3hCdAWC5eYg1slXmdFzPMABn0SpvkGewBYkc3Q6IJlO7yyOSrHULgKmbUB+2kaOGaZD1r52BUDyy+VitnwGN8jue7U0WKJkoKRB3UFQ/zv4bYnybdO4VJb6dXSxnmvluO7VU/NVusi9iLyR8J0XoZTwjzTZijHmKqIj1jtnGB9iodYUM/3DvwomiFDiH7FveYJ1WpIC3p/c/2ednBHqL2rZ1FLffwEF++/actXho2RWsTEdamHRDM+WMzW7Ji4dvdz/9e4fTe+zFcg1165TbICMZcoD5kbSxQvvL0qCMmP+sLcLIcY8UJc="
rvm:
  - 2.5
before_script:
  - psql -c 'CREATE DATABASE ecommerce_test' -U postgres
  - bundle exec rails db:migrate
  - echo $RAILS_MASTER_KEY
script:
  - bundle exec rspec -fd
  - bundle exec rubocop -P
